project:
  type: website
  output-dir: docs

website:
  title: "Jenna Worthen - Data Science Portfolio"
  description: "A showcase of my data science projects and learning journey"
  
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.md
      - text: "About Me"
        href: about.md
      - text: "Blog"  # New Blog tab added here
        href: blog.md
      - text: "Projects"
        menu:
          - text: "All Projects"
            href: projects/index.md
          - text: "Golf Analytics Research"
            href: projects/golf.md
          - text: "NFL Big Data Bowl 2025"
            href: projects/nfl.md
          - text: "Data Acquisition: Basketball Scouting"
            href: projects/data-acquisition.md
          - text: "Final Project"
            href: projects/final-project.qmd
          - text: "Exploratory Data Analysis"
            href: projects/eda.qmd

    right:
      - icon: github
        href: https://github.com/cottonjenn
      - icon: linkedin
        href: https://www.linkedin.com/in/jenna-worthen-b9a8b2299/

  sidebar:
    - title: "Projects"
      contents:
        - projects/index.md
        - projects/golf.md
        - projects/nfl.md
        - projects/data-acquisition.md
        - projects/final-project.qmd
        - projects/eda.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css